# Generated by Django 3.1.6 on 2021-02-10 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Name')),
                ('contact', models.CharField(default='', max_length=300, verbose_name='Contact (Phone/Email)')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date and time')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='Project title')),
                ('description', models.TextField()),
                ('start_date', models.DateField(null=True, verbose_name='Project start date')),
                ('end_date', models.DateField(null=True, verbose_name='Project end date')),
                ('category', models.CharField(choices=[(0, 'Residential'), (1, 'Hospitality & Commercial')], max_length=100, verbose_name='Project category')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_gallery')),
                ('category', models.CharField(choices=[(0, 'Indoor'), (1, 'Outdoor'), (2, 'Top view')], max_length=100, verbose_name='Image category')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.project')),
            ],
        ),
    ]
