# Generated by Django 3.1.6 on 2021-02-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[(0, 'Residential'), (1, 'Hospitality & Commercial')], max_length=1, verbose_name='Project category'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='category',
            field=models.CharField(choices=[(0, 'Indoor'), (1, 'Outdoor'), (2, 'Top view')], max_length=1, verbose_name='Image category'),
        ),
    ]
