# Generated by Django 3.1.6 on 2021-02-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
