# Generated by Django 3.1.6 on 2021-03-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210226_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='user_img/', verbose_name='Client Image')),
                ('name', models.CharField(max_length=100)),
                ('review', models.TextField()),
            ],
        ),
    ]
